version: 3
services:
 db:
    image: postgres
    ports:
    - 5432:5432
    networks:
    - backend

 my-app:
    build: ./
    ports:
    - 8080:8080
    networks:
    - backend
    
networks:
 backend:
