version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    networks:
    - backend
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
    - backend
      
  my-app:
    build: ./
    ports:
    - 8080:8080
    networks:
     - backend
    volumes:
     - /root/.m2/repository/:/root/.m2/repository/
    
networks:
 backend:


